import Topbar from "@/app/components/Molecular/topbar";
import Navbar from "@/app/components/Organism/navBar";
import { Space_Grotesk } from "next/font/google";

const inter = Space_Grotesk({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">

            <body className={`h-screen overflow-hidden ${inter.className} overflow-hidden`}>
                <div className="h-screen relative lg:w-1/5 md:w-1/2 mx-auto text-white">
                    <Topbar />
                    {children}
                    <div className="absolute w-full bottom-0">
                    <Navbar />
                    </div>
                </div>
            </body>
        </html>
    );
}
