import { Space_Grotesk } from "next/font/google";
import Topbar from "../components/Molecular/topbar";
import Navbar from "../components/Organism/navBar";

const inter = Space_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "Note-Ation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={` ${inter.className} overflow-hidden`}>
        <div className="lg:w-1/5 h-screen relative  md:w-1/2 mx-auto text-white">
          <Topbar />
          {children}
          <div className="absolute w-full bottom-0">
            <Navbar />
          </div>
        </div>
      </body>
    </html>
  );
}
